#!/usr/bin/env bash
# Patches the installed /usr/local/bin/airsnitch-run with the latest version.

TARGET=/usr/local/bin/airsnitch-run

cat > "${TARGET}" << 'EOF'
#!/usr/bin/env bash
# airsnitch-run — one-command launcher for the AirSnitch CLI attack tool.
# Must be run as root (raw socket access required).
#
# Auto-scans for the target SSID, picks the best 2.4GHz frequency (falls
# back to 5GHz) and restricts wpa_supplicant to that single frequency so
# only one AP is reachable — no bssid= needed, no --same-bss conflicts.
set -euo pipefail

RESEARCH_DIR="/opt/airsnitch/airsnitch/research"
CONF="${RESEARCH_DIR}/client.conf"

if grep -q 'ssid="testnetwork"' "${CONF}" 2>/dev/null; then
    echo "[!] client.conf still has default values. Edit it first: nano ${CONF}"
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

# ── Find base wireless interface (no airmon-ng) ───────────────────────────────
# Optional $1 argument: explicitly specify the interface (used by web GUI).
# Without $1: auto-detect — skip monitor interfaces (wpa_supplicant cannot
# set wlan0mon to STATION mode).
if [[ -n "${1:-}" ]] && [[ "${1:-}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    IFACE="${1}"
    # Strip monitor-mode suffix — wpa_supplicant cannot use monitor interfaces
    if [[ "${IFACE}" =~ mon$ ]]; then
        IFACE="${IFACE%mon}"
        echo "[*] Stripping monitor suffix → using ${IFACE} (base interface)"
    else
        echo "[*] Interface: ${IFACE} (specified)"
    fi
else
    IFACE=$(iw dev 2>/dev/null | awk '/Interface/{print $2}' \
        | { grep -vE 'mon$' || true; } | head -1)

    if [[ -z "${IFACE}" ]]; then
        MON_IFACE=$(iw dev 2>/dev/null | awk '/Interface/{print $2}' \
            | { grep -E 'mon$' || true; } | head -1)
        if [[ -n "${MON_IFACE}" ]]; then
            IFACE="${MON_IFACE%mon}"
            echo "[*] Removing monitor interface ${MON_IFACE} — using ${IFACE} directly"
            iw dev "${MON_IFACE}" del 2>/dev/null || true
            sleep 1
            ip link set "${IFACE}" up 2>/dev/null || true
        fi
    fi

    [[ -z "${IFACE}" ]] && { echo "[!] No wireless interfaces found."; exit 1; }
fi

# ── Release from NetworkManager without stopping it ──────────────────────────
nmcli device set "${IFACE}" managed no 2>/dev/null || true
trap 'nmcli device set "${IFACE}" managed yes 2>/dev/null || true' EXIT

# ── Read credentials from client.conf ────────────────────────────────────────
TARGET_SSID=$(grep -v '^\s*#' "${CONF}" | grep 'ssid=' | head -1 | sed 's/.*ssid="\(.*\)"/\1/')
TARGET_PSK=$( grep -v '^\s*#' "${CONF}" | grep 'psk='  | head -1 | sed 's/.*psk="\(.*\)"/\1/')
CTRL_IFACE=$( grep 'ctrl_interface=' "${CONF}"          | head -1 | sed 's/ctrl_interface=//')

# ── Scan: find frequencies the target SSID is broadcasting on ────────────────
echo "[*] Scanning for '${TARGET_SSID}' on ${IFACE}..."
ip link set "${IFACE}" up 2>/dev/null || true
SCAN_RAW=$(iw dev "${IFACE}" scan 2>/dev/null || true)

# Use int() to strip decimal points (iw sometimes outputs "2412.0" not "2412")
SCAN_DETAIL=$(echo "${SCAN_RAW}" | awk -v target="${TARGET_SSID}" '
    /^BSS /        { bssid = $2; sub(/\(.*/, "", bssid); freq = "" }
    /^\s+freq:/    { freq = int($2) }
    /^\s+SSID: /   {
        ssid = substr($0, index($0, "SSID: ") + 6)
        if (ssid == target && freq != "") print bssid "\t" freq
    }
')

if [[ -z "${SCAN_DETAIL}" ]]; then
    echo "[!] '${TARGET_SSID}' not found — check adapter is up and in range."
    echo "    Falling back to all 2.4GHz channels."
    TARGET_FREQ="2412"
    FREQ_LIST="2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462"
else
    # Prefer 2.4GHz (2400-2500 MHz) for stable rapid reconnects on mesh networks.
    # With freq_list set to a single frequency, wpa_supplicant only sees one AP —
    # no bssid= needed, no roaming between mesh nodes, no --same-bss conflicts.
    BEST=$(echo "${SCAN_DETAIL}" | awk '$2 >= 2400 && $2 < 3000 {print; exit}')
    if [[ -z "${BEST}" ]]; then
        BEST=$(echo "${SCAN_DETAIL}" | awk 'NR==1')
        echo "[!] No 2.4GHz AP found — using 5GHz (may be less stable for rapid reconnects)."
    fi
    TARGET_BSSID=$(echo "${BEST}" | awk '{print $1}')
    TARGET_FREQ=$(echo "${BEST}"  | awk '{print $2}')
    FREQ_LIST="${TARGET_FREQ}"
    echo "[+] '${TARGET_SSID}' found at ${TARGET_BSSID} (${TARGET_FREQ} MHz)"
fi

# ── Write temporary client.conf (never modifies the user's client.conf) ───────
# No bssid= in config — freq_list restricted to a single frequency is enough
# to ensure both connections land on the same AP. Adding bssid= triggers a
# different code path in airsnitch.py that conflicts with --same-bss.
TEMP_CONF=$(mktemp /tmp/airsnitch-client.XXXXXX.conf)
trap 'rm -f "${TEMP_CONF}"; nmcli device set "${IFACE}" managed yes 2>/dev/null || true' EXIT

cat > "${TEMP_CONF}" << CONFEOF
# Generated by airsnitch-run — edit ${CONF} to change SSID/PSK.
# Don't change this line, otherwise AirSnitch won't work
ctrl_interface=${CTRL_IFACE:-wpaspy_ctrl}

network={
        # Don't change this line, otherwise AirSnitch won't work
        id_str="victim"

        ssid="${TARGET_SSID}"
        key_mgmt=WPA-PSK
        psk="${TARGET_PSK}"

        scan_freq=${TARGET_FREQ}
        freq_list=${FREQ_LIST}
}

network={
        # Don't change this line, otherwise AirSnitch won't work
        id_str="attacker"

        ssid="${TARGET_SSID}"
        key_mgmt=WPA-PSK
        psk="${TARGET_PSK}"

        scan_freq=${TARGET_FREQ}
        freq_list=${FREQ_LIST}
}
CONFEOF

echo "[+] Using interface: ${IFACE}"
echo "[*] Starting AirSnitch — press Ctrl+C to stop."
echo ""

cd "${RESEARCH_DIR}"
exec venv/bin/python3 ./airsnitch.py "${IFACE}" \
    --config "${TEMP_CONF}" \
    --check-gtk-shared "${IFACE}" \
    --same-bss
EOF

chmod +x "${TARGET}"
echo "[+] Fixed: ${TARGET}"
echo "Now run: sudo airsnitch-run"
