#!/usr/bin/env bash
# Patches the installed /usr/local/bin/airsnitch-run with the latest version:
#   - Auto-scans for target SSID frequencies (2.4GHz and 5GHz)
#   - Prefers 2.4GHz for stability, falls back to 5GHz if needed
#   - Releases interface from NetworkManager without killing it
#   - Writes a temp config with detected freq_list — never modifies client.conf
#   - Passes --same-bss automatically

TARGET=/usr/local/bin/airsnitch-run

cat > "${TARGET}" << 'EOF'
#!/usr/bin/env bash
# airsnitch-run — one-command launcher for the AirSnitch CLI attack tool.
# Must be run as root (raw socket access required).
#
# Auto-detects the target network's frequencies via a live scan and builds
# a temporary config — no manual freq_list editing required.
set -euo pipefail

RESEARCH_DIR="/opt/airsnitch/airsnitch/research"
CONF="${RESEARCH_DIR}/client.conf"

# Sanity: refuse to run with unedited defaults
if grep -q 'ssid="testnetwork"' "${CONF}" 2>/dev/null; then
    echo ""
    echo "[!] client.conf still contains the default placeholder values."
    echo "    Edit it first, then re-run airsnitch-run:"
    echo "    nano ${CONF}"
    echo ""
    exit 1
fi

# Require root
if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

# ── Find base wireless interface (skip airmon-ng entirely) ────────────────────
IFACE=$(iw dev 2>/dev/null | awk '/Interface/{print $2}' \
    | { grep -vE 'mon$' || true; } | head -1)

if [[ -z "${IFACE}" ]]; then
    MON_IFACE=$(iw dev 2>/dev/null | awk '/Interface/{print $2}' \
        | { grep -E 'mon$' || true; } | head -1)
    if [[ -n "${MON_IFACE}" ]]; then
        IFACE="${MON_IFACE%mon}"
        echo "[*] Removing monitor interface ${MON_IFACE} — using ${IFACE} directly"
        iw dev "${MON_IFACE}" del 2>/dev/null || true
        sleep 1
        ip link set "${IFACE}" up 2>/dev/null || true
    fi
fi

if [[ -z "${IFACE}" ]]; then
    echo "[!] No wireless interfaces found. Plug in your adapter and retry."
    exit 1
fi

# ── Release interface from NetworkManager ────────────────────────────────────
nmcli device set "${IFACE}" managed no 2>/dev/null || true
trap 'nmcli device set "${IFACE}" managed yes 2>/dev/null || true' EXIT

# ── Read target SSID and PSK from client.conf ────────────────────────────────
TARGET_SSID=$(grep -v '^\s*#' "${CONF}" | grep 'ssid=' | head -1 \
    | sed 's/.*ssid="\(.*\)"/\1/')
TARGET_PSK=$(grep -v '^\s*#' "${CONF}" | grep 'psk=' | head -1 \
    | sed 's/.*psk="\(.*\)"/\1/')
CTRL_IFACE=$(grep 'ctrl_interface=' "${CONF}" | head -1 \
    | sed 's/ctrl_interface=//')

# ── Auto-scan: detect frequencies the target AP is broadcasting on ────────────
echo "[*] Scanning for '${TARGET_SSID}' on ${IFACE}..."
ip link set "${IFACE}" up 2>/dev/null || true
SCAN_RAW=$(iw dev "${IFACE}" scan 2>/dev/null || true)

FOUND_FREQS=$(echo "${SCAN_RAW}" | awk -v target="${TARGET_SSID}" '
    /^BSS /        { freq = "" }
    /^\s+freq:/    { freq = $2 }
    /^\s+SSID: /   {
        ssid = substr($0, index($0, "SSID: ") + 6)
        if (ssid == target && freq != "") print freq
    }
' | sort -u | tr '\n' ' ' | sed 's/ $//')

if [[ -z "${FOUND_FREQS}" ]]; then
    echo "[!] '${TARGET_SSID}' not found in scan — check adapter is up and in range."
    echo "    Falling back to all 2.4GHz channels."
    FOUND_FREQS="2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462"
fi

# Prefer 2.4GHz (more stable for rapid reconnects); fall back to 5GHz if needed
FREQS_2G=$(echo "${FOUND_FREQS}" | tr ' ' '\n' \
    | { grep -E '^2[0-9]{3}$' || true; } | tr '\n' ' ' | sed 's/ $//')
FREQS_5G=$(echo "${FOUND_FREQS}" | tr ' ' '\n' \
    | { grep -E '^5[0-9]{3}$' || true; } | tr '\n' ' ' | sed 's/ $//')

if [[ -n "${FREQS_2G}" ]]; then
    FREQ_LIST="${FREQS_2G}"
    echo "[+] '${TARGET_SSID}' found on 2.4GHz: ${FREQ_LIST}"
elif [[ -n "${FREQS_5G}" ]]; then
    FREQ_LIST="${FREQS_5G}"
    echo "[+] '${TARGET_SSID}' found on 5GHz: ${FREQ_LIST}"
    echo "[!] 5GHz only — rapid reconnects may be less stable on some adapters."
else
    FREQ_LIST="${FOUND_FREQS}"
    echo "[+] '${TARGET_SSID}' found on: ${FREQ_LIST}"
fi

FIRST_FREQ=$(echo "${FREQ_LIST}" | awk '{print $1}')

# ── Write temporary client.conf with detected freq_list ──────────────────────
TEMP_CONF=$(mktemp /tmp/airsnitch-client.XXXXXX.conf)
trap 'rm -f "${TEMP_CONF}"; nmcli device set "${IFACE}" managed yes 2>/dev/null || true' EXIT

cat > "${TEMP_CONF}" << CONFEOF
# Generated by airsnitch-run — edit ${CONF} to change SSID/PSK.
# Don't change this line, otherwise AirSnitch won't work
ctrl_interface=${CTRL_IFACE:-wpaspy_ctrl}

network={
        # Don't change this line, otherwise AirSnitch won't work
        id_str="victim"

        ssid="${TARGET_SSID}"
        key_mgmt=WPA-PSK
        psk="${TARGET_PSK}"

        scan_freq=${FIRST_FREQ}
        freq_list=${FREQ_LIST}
}

network={
        # Don't change this line, otherwise AirSnitch won't work
        id_str="attacker"

        ssid="${TARGET_SSID}"
        key_mgmt=WPA-PSK
        psk="${TARGET_PSK}"

        scan_freq=${FIRST_FREQ}
        freq_list=${FREQ_LIST}
}
CONFEOF

echo "[+] Using interface: ${IFACE}"
echo "[*] Starting AirSnitch — press Ctrl+C to stop."
echo ""

cd "${RESEARCH_DIR}"
exec venv/bin/python3 ./airsnitch.py "${IFACE}" \
    --config "${TEMP_CONF}" \
    --check-gtk-shared "${IFACE}" \
    --same-bss
EOF

chmod +x "${TARGET}"
echo "[+] Fixed: ${TARGET}"
echo ""
echo "Now run: sudo airsnitch-run"
